name: shop0koa_frontend
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6
  dotted_border: ^2.1.0
  file_picker: ^8.0.3
  firebase_core: ^3.0.0
  firebase_storage: ^12.0.0
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  google_fonts: ^6.2.1
  http: ^1.2.1
  image_picker: ^1.1.2
  json_annotation: ^4.9.0
  logger: ^2.3.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
  #  - assets/icons/
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
